# Generated by Django 2.0.2 on 2018-02-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
                ('image', models.CharField(max_length=300)),
                ('video', models.CharField(max_length=300)),
                ('level', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=70)),
                ('popularity', models.IntegerField()),
                ('estimated_time', models.IntegerField()),
            ],
        ),
    ]
