# Generated by Django 2.0.2 on 2018-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['popularity']},
        ),
        migrations.AddField(
            model_name='food',
            name='utensils',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='author',
            field=models.CharField(default='Telande', max_length=70),
        ),
        migrations.AlterField(
            model_name='food',
            name='level',
            field=models.CharField(default='Easy', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='video',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
